name: dus_app_1
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  intl: ^0.18.0
  flutter:
    sdk: flutter
  
  # --- MEVCUT PAKETLERİN ---
  confetti: ^0.7.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  shared_preferences: ^2.5.4

  # --- ODAK MODU İÇİN YENİ EKLENENLER ---
  percent_indicator: ^4.2.3        # Dairesel sayaç tasarımı için
  wakelock_plus: ^1.1.4            # Sayaç çalışırken ekran kapanmasın diye
  flutter_local_notifications: ^17.2.2 # Süre bitince bildirim göndermek için
  
  # Animasyon dosyan (loading_dent.json) var ama lottie paketi eksikti, onu da ekledim:
  lottie: ^3.1.0

  # --- İSTATİSTİK SAYFASI İÇİN EKLENEN ---
  fl_chart: ^0.68.0  # Grafikleri çizdirmek için gerekli paket

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # --- ASSETS (MEVCUT AYARLARIN) ---
  assets:
    - assets/animations/loading_dent.json
    - assets/images/logo.png
    - assets/data/anatomi.json
    - assets/data/

  # --- FONTS (MEVCUT AYARLARIN) ---
  fonts:
     - family: Fish
       fonts:
         - asset: assets/fonts/Fish.ttf